spring:
  application:
    name: ClientManager

  h2:
    console:
      enabled: true
      path: /database

  datasource:
    url: jdbc:h2:file:./data/database;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 2400000
  refresh-token-expiration: 48000000